baseURL = 'https://buff.cooking/'
languageCode = 'en-us'
title = 'Buff Cooking'
theme = 'lugo'

[params]
favicon = "/favicon.svg"
stylesheet = "/style.css"
indexarticles = 50
taglist = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
